version:  '4.26.1'

services:
  db:
    image: mysql:8.0.36
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: payments
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: